// * Clients are autogenerated
// * run ~npx prisma generate
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

interface UpdateParams {
  firstName: string;
  lastName: string;
}

async function inserUser(
  email: string,
  password: string,
  firstName?: string,
  lastName?: string
) {
  const res = await prisma.user.create({
    data: {
      email,
      password,
      firstName,
      lastName,
    },
    select: {
      id: true,
      password: true,
    },
  });
  console.log(res);
}

// inserUser("sai@gmail.com", "biryaniislub", "sai", "kiran");

async function updateUser(
  email: string,
  { firstName, lastName }: UpdateParams
) {
  const res = await prisma.user.update({
    where: { email },
    data: {
      firstName,
      lastName,
    },
  });
  console.log(res);
}

// updateUser("sai@gmail.com", { firstName: "polaki", lastName: "sai" });

async function fetchUser(email: string) {
  const res = await prisma.user.findFirst({
    where: { email },
  });
  console.log(res);
}

fetchUser("sai@gmail.com");
